extends Node2D

const character_select_spritesheet = {
	0: preload("res://src/img/items/sandwich.svg"),
	1: preload("res://src/img/select/1_select.png"),
	2: preload("res://src/img/select/2_select.png"),
	3: preload("res://src/img/select/3_select.png"),
	4: preload("res://src/img/select/4_select.png"),
	5: preload("res://src/img/select/5_select.png"),
	6: preload("res://src/img/select/6_select.png"),
	7: preload("res://src/img/select/7_select.png"),
	8: preload("res://src/img/select/8_select.png"),
	9: preload("res://src/img/select/9_select.png"),
	10: preload("res://src/img/select/10_select.png"),
	11: preload("res://src/img/select/11_select.png"),
	12: preload("res://src/img/select/12_select.png"),
	13: preload("res://src/img/select/13_select.png"),
	14: preload("res://src/img/select/14_select.png"),
	15: preload("res://src/img/select/15_select.png"),
	16: preload("res://src/img/select/16_select.png"),
	17: preload("res://src/img/select/17_select.png"),
	18: preload("res://src/img/select/18_select.png"),
	19: preload("res://src/img/select/19_select.png"),
	20: preload("res://src/img/select/20_select.png"),
	21: preload("res://src/img/select/21_select.png"),
	22: preload("res://src/img/select/22_select.png"),
	23: preload("res://src/img/select/23_select.png"),
	24: preload("res://src/img/select/24_select.png"),
	25: preload("res://src/img/select/25_select.png"),
	26: preload("res://src/img/select/26_select.png"),
	27: preload("res://src/img/select/27_select.png"),
	28: preload("res://src/img/select/28_select.png"),
	29: preload("res://src/img/select/29_select.png"),
	30: preload("res://src/img/select/30_select.png"),
	31: preload("res://src/img/select/1_select.png"), # Where is Hatty?
	32: preload("res://src/img/select/21_select.png"),
	33: preload("res://src/img/select/33_select.png"),
	34: preload("res://src/img/select/34_select.png"),
};
