extends Node2D

const character_select_spritesheet = {
	0: preload("res://src/img/items/sandwich.svg"),
	1: preload("res://src/img/select/1_select.svg"),
	2: preload("res://src/img/select/2_select.svg"),
	3: preload("res://src/img/select/3_select.svg"),
	4: preload("res://src/img/select/4_select.svg"),
	5: preload("res://src/img/select/5_select.svg"),
	6: preload("res://src/img/select/6_select.svg"),
	7: preload("res://src/img/select/7_select.svg"),
	8: preload("res://src/img/select/8_select.svg"),
	9: preload("res://src/img/select/9_select.svg"),
	10: preload("res://src/img/select/10_select.svg"),
	11: preload("res://src/img/select/11_select.svg"),
	12: preload("res://src/img/select/12_select.svg"),
	13: preload("res://src/img/select/13_select.svg"),
	14: preload("res://src/img/select/14_select.svg"),
	15: preload("res://src/img/select/15_select.svg"),
	16: preload("res://src/img/select/16_select.svg"),
	17: preload("res://src/img/select/17_select.svg"),
	18: preload("res://src/img/select/18_select.svg"),
	19: preload("res://src/img/select/19_select.svg"),
	20: preload("res://src/img/select/20_select.svg"),
	21: preload("res://src/img/select/21_select.svg"),
	22: preload("res://src/img/select/22_select.svg"),
	23: preload("res://src/img/select/23_select.svg"),
	24: preload("res://src/img/select/24_select.svg"),
	25: preload("res://src/img/select/25_select.svg"),
	26: preload("res://src/img/select/26_select.svg"),
	27: preload("res://src/img/select/27_select.svg"),
	28: preload("res://src/img/select/28_select.svg"),
	29: preload("res://src/img/select/29_select.svg"),
	30: preload("res://src/img/select/30_select.svg"),
	31: preload("res://src/img/select/1_select.svg"), # Where is Hatty?
	32: preload("res://src/img/select/21_select.svg"),
};
